name: ammotiobyshelbourne
version: 1.0.8
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  dio: ^5.4.0
  url_launcher: ^6.2.4
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  responsive_builder: ^0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iosicon.png"
  min_sdk_android: 21

flutter: 
  assets:
    - assets/images/
  uses-material-design: true

