import 'package:flutter/material.dart';

class AppColors {
  static const Color primaryColor = Color(0xFF313C52);
  static const Color accentColor = Color(0xFF313C52);
  static const Color splashColor = Color(0xFF313C52);
  static const Color lightPrimaryColor = Color(0xFF3D4B66);
  static const Color lighterPrimaryColor = Color(0xFF414D66);
  static const Color highlightColor = Color(0xFF313C52);
  static const Color dividerColor = Color(0xff343a40);
  static const Color errorColor = Color(0xffDF4756);
  static const Color transparent = Colors.transparent;

  static const Color white = Color(0xFFFFFFFF);
  static const Color amber = Color(0xFFFFC107);
  static const Color grey = Color(0xFF9E9E9E);
  static Color greyShade100 = Colors.grey.shade100;
  static Color greyShade200 = Colors.grey.shade200;
  static Color greyShade300 = Colors.grey.shade300;
  static Color greyShade400 = Colors.grey.shade400;
  static Color greyShade600 = Colors.grey.shade600;
  static const Color mediumGrey = Color(0xFF787878);
  static const Color darkGrey = Color(0xFF595858);
  static const Color blue = Colors.blue;
  static Color darkBlue = Colors.blue.shade800;
  static const Color blueGrey = Colors.blueGrey;
  static const Color red = Colors.red;
  static const Color darkRed = Color(0xFFb71c1c);
  static const Color black = Color(0xFF000000);
  static const Color green = Colors.green;
  static const Color darkGreen = Color(0xFF398D3C);
  static const Color lighterGrey = Color(0xFFEDEDED);
  static const Color lightGrey = Color(0xFFF6F6F6);
  static const Color dividerGrey = Color(0xFFD1D1D1);
  static const Color backgroundColor = Color(0xFFF3F8FE);
  static const Color lightCream = Color(0xFFF9F2D3);
  static const Color lightRed = Color(0xFFA20C33);
  static const Color lightRedColor = Color(0xFFF6E7EB);
  static const Color pendingColor = Color(0xFFF9F2D3);
  static const Color completedColor = Color(0xFFE7F9ED);
  static const Color pendingTextColor = Color(0xFFE1B814);
  static Color awaitingTextColor = Colors.amber.shade800;
  static const Color lightGreenColor = Color(0xFFD0E5D9);
  static const Color lightCardColor = Color(0xFFF6E7EB);
  static const Color dividerDarkColor = Color(0xFF4E4E4E);
  static const Color lightBlackBorderColor = Color(0xFFEBEBEB);
  static const Color lightBlackColor = Color(0xFFFAFAFA);
  static const Color snackBarBgColor = Color(0xFFFFF2F6);
  static const Color lightBorderColor = Color(0xFFF2F2F2);
  static const Color lightGreenBorder = Color(0xFFE7F2EC);
  static const Color payslipColor = Color(0xFF2AC3FF);
  static const Color workHoursColor = Color(0xFF9269FD);
  static const Color invoiceColor = Color(0xFFFF8F61);
  static const Color expensesColor = Color(0xFF96DA45);
}
